//
// Created by School on 11/1/17.
//

#ifndef ECE_1160_LAB_3_REAL_TIME_SCHEDULING_OVER_LINUX_DUMMY_H
#define ECE_1160_LAB_3_REAL_TIME_SCHEDULING_OVER_LINUX_DUMMY_H

void foo();
#endif //ECE_1160_LAB_3_REAL_TIME_SCHEDULING_OVER_LINUX_DUMMY_H
